TimTest/TimTest/Models/Abstract/Layout.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TimTest.Models.Abstract
{
    public abstract class Layout
    {
        public Layout()
        {
            ErrorMessages = new List<string>();
            SuccessMessages = new List<string>();
            InfoMessages = new List<string>();
        }

        public ICollection<string> SuccessMessages { get; set; }
        public ICollection<string> InfoMessages { get; set; }
        public ICollection<string> ErrorMessages { get; set; }
    }
}

TimTest/TimTest/Models/ErrorViewModel.cs
using System;

namespace TimTest.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TimTest/TimTest/Models/EuropePMCModels.cs
using PMC;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TimTest.Infrastructure.Extensions.Abstract;
using TimTest.Infrastructure.Templates;
using TimTest.Models.Abstract;

namespace TimTest.Models
{
    public class SearchPublicationModels : Layout
    {
        public SearchPublicationModels()
        {
            Page = 1;
        }

        public string Query { get; set; }
        public int Page { get; set; }
    }

    public class ReadPublications : Layout
    {
        public ReadPublications()
        {

        }

        public ReadPublications(int page)
        {
            Page = page;
        }

        public int Page { get; set; }
        public string Query { get; set; }

        public IPagedList<PMCSearchResponse> Publications { get; set; }
    }
}

TimTest/TimTest/Controllers/Abstract/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FluentValidation.Results;
using Microsoft.AspNetCore.Mvc;

namespace TimTest.Controllers.Abstract
{
    public abstract class BaseController : Controller
    {
        protected IEnumerable<string> GetValidatorMessages(IEnumerable<ValidationFailure> validationResults)
        {
            foreach (var error in validationResults.Select(w => w.ErrorMessage))
                yield return error;
        }
    }
}

TimTest/TimTest/Controllers/EuropePmcController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PMC;
using TimTest.Controllers.Abstract;
using TimTest.Infrastructure.Extensions;
using TimTest.Infrastructure.Services;
using TimTest.Infrastructure.Services.Abstract;
using TimTest.Infrastructure.Validators;
using TimTest.Models;

namespace TimTest.Controllers
{
    public class EuropePmcController : BaseController
    {
        private IEuropePmcService _europePmcService = new EuropePmcService();

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ReadPublications(SearchPublicationModels inModel)
        {
            var validator = new SearchPublicationModelsValidator().Validate(inModel);
            var outModel = new ReadPublications(inModel.Page);

            if (validator.IsValid)
            {
                outModel.Publications = _europePmcService
                    .GetPublications(inModel.Query, inModel.Page)
                    .ToPagedList(25, inModel.Page);

                if (outModel.Publications.Count() == 0)
                    outModel.InfoMessages.Add("No publications was found");
            }
            else
                outModel.ErrorMessages = base.GetValidatorMessages(validator.Errors).ToList();

            return View(outModel);
        }
    }
}

TimTest/TimTest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TimTest.Models;

namespace TimTest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TimTest/TimTest/Views/EuropePMC/Index.cshtml
@model TimTest.Models.SearchPublicationModels
<html>
<head>

</head>
<body>
    <div class="container">
        <div class="row mb-4">
            <div class="col-12 col-md-4"></div>
            <div class="col-12 col-md-4 text-center">

                @using (Html.BeginForm("ReadPublications", "EuropePMC", FormMethod.Post))
                {
                    @Html.AntiForgeryToken();
                    <h5>Search publications</h5>

                    @Html.TextBoxFor(d => d.Query, null, new { @class = "form-control", @maxlength = "50", @placeholder = "Type in something", @required = true, @type = "text", @id = "searchInput", @onfocusout = "SearchPublicationsValidator()" })
                    <button type="submit" class="btn btn-block btn-primary mt-3">Search</button>
                }

            </div>
            <div class="col-12 col-md-4"></div>
        </div>
    </div>

    <script>

        function SearchPublicationsValidator() {
            $('searchInput');
        }

    </script>

</body>
</html>

TimTest/TimTest/Views/EuropePMC/ReadPublications.cshtml
@model TimTest.Models.ReadPublications
<html>
<head>

</head>
<body>
    <div class="container">

        @if (Model?.Publications != null)
        {
            <div class="col-12 mb-4">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Autors</th>
                            <th>Date</th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var x in Model.Publications)
                        {
                            <tr>
                                <td>@x.Title</td>
                                <td>@x.Authors</td>
                                <td>@x.DatePublished</td>
                            </tr>
                        }

                    </tbody>
                </table>

                @{
                    int nextpage = (Model.Page + 1);
                    int prevpage = 0;

                    if (Model.Page > 1)
                        prevpage = (Model.Page - 1);
                }

                @using (Html.BeginForm("ReadPublications", "EuropePMC", FormMethod.Post))
                {
                    @Html.HiddenFor(d => d.Query);
                    <div class="row">
                        <div class="col-md-5 col-12"></div>
                        <div class="col-md-2 col-12">
                            <ul class="pagination">

                                @if (Model.Page == 1)
                                {
                                    <li class="page-item"><button disabled class="page-link disabled">Previous</button></li>
                                }
                                else
                                {
                                    <li class="page-item">
                                        <button value="@prevpage" id="next" name="Page" type="submit" class="page-link">Previous</button>
                                    </li>
                                }

                                <li class="page-item">
                                    <button value="@nextpage" id="prev" name="Page" type="submit" class="page-link">Next</button>
                                </li>

                            </ul>
                        </div>
                        <div class="col-md-5 col-12"></div>
                    </div>
                }

            </div>

        }

    </div>

</body>
</html>

TimTest/TimTest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

TimTest/TimTest/Views/Shared/_Layout.cshtml
@model TimTest.Models.Abstract.Layout
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TimTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TimTest</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EuropePmc" asp-action="Index">Search</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">

            @if (Model?.SuccessMessages != null)
            {
                foreach (var message in Model.SuccessMessages)
                {
                    <div class="alert alert-success text-center" role="alert">@message</div>
                }
            }

            @if (Model?.InfoMessages != null)
            {
                foreach (var message in Model.InfoMessages)
                {
                    <div class="alert alert-primary text-center" role="alert">@message</div>
                }
            }

            @if (Model?.ErrorMessages != null)
            {
                foreach (var message in Model.ErrorMessages)
                {
                    <div class="alert alert-warning text-center" role="alert">@message</div>
                }
            }

            @RenderBody()

        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TimTest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>